In [1]:
import numpy as np

def generate_data():
    # 本函数生成0-9，10个数字的图片矩阵
    image_data=[]
    num_0 = np.array(
    [[0,0,1,1,0,0],
    [0,1,0,0,1,0],
    [0,1,0,0,1,0],
    [0,1,0,0,1,0],
    [0,0,1,1,0,0],
    [0,0,0,0,0,0]])
    image_data.append(num_0)
    num_1 = np.array(
    [[0,0,0,1,0,0],
    [0,0,1,1,0,0],
    [0,0,0,1,0,0],
    [0,0,0,1,0,0],
    [0,0,1,1,1,0],
    [0,0,0,0,0,0]])
    image_data.append(num_1)
    num_2 = np.array(
    [[0,0,1,1,0,0],
    [0,1,0,0,1,0],
    [0,0,0,1,0,0],
    [0,0,1,0,0,0],
    [0,1,1,1,1,0],
    [0,0,0,0,0,0]])
    image_data.append(num_2)
    num_3 = np.array(
    [[0,0,1,1,0,0],
    [0,0,0,0,1,0],
    [0,0,1,1,0,0],
    [0,0,0,0,1,0],
    [0,0,1,1,0,0],
    [0,0,0,0,0,0]])
    image_data.append(num_3)
    num_4 = np.array(
    [
    [0,0,0,0,1,0],
    [0,0,0,1,1,0],
    [0,0,1,0,1,0],
    [0,1,1,1,1,1],
    [0,0,0,0,1,0],
    [0,0,0,0,0,0]])
    image_data.append(num_4)
    num_5 = np.array(
    [
    [0,1,1,1,0,0],
    [0,1,0,0,0,0],
    [0,1,1,1,0,0],
    [0,0,0,0,1,0],
    [0,1,1,1,0,0],
    [0,0,0,0,0,0]])
    image_data.append(num_5)
    num_6 = np.array(
    [[0,0,1,1,0,0],
    [0,1,0,0,0,0],
    [0,1,1,1,0,0],
    [0,1,0,0,1,0],
    [0,0,1,1,0,0],
    [0,0,0,0,0,0]])
    image_data.append(num_6)
    num_7 = np.array(
    [
    [0,1,1,1,1,0],
    [0,0,0,0,1,0],
    [0,0,0,1,0,0],
    [0,0,0,1,0,0],
    [0,0,0,1,0,0],
    [0,0,0,0,0,0]])
    image_data.append(num_7)
    num_8 = np.array(
    [[0,0,1,1,0,0],
    [0,1,0,0,1,0],
    [0,0,1,1,0,0],
    [0,1,0,0,1,0],
    [0,0,1,1,0,0],
    [0,0,0,0,0,0]])
    image_data.append(num_8)
    num_9 = np.array(
    [[0,0,1,1,1,0],
    [0,1,0,0,1,0],
    [0,0,1,1,1,0],
    [0,0,0,0,1,0],
    [0,0,0,0,1,0],
    [0,0,0,0,0,0]])
    image_data.append(num_9)
    return image_data

In [2]:
def get_feature(x):
    return np.sum(x,0)

In [3]:
img=generate_data()
all_feature = []
for i in img:
    all_feature.append(get_feature(i))
all_feature=np.array(all_feature)
print(all_feature)

[[0 3 2 2 3 0]
 [0 0 2 5 1 0]
 [0 2 3 3 2 0]
 [0 0 3 3 2 0]
 [0 1 2 2 5 1]
 [0 4 3 3 1 0]
 [0 3 3 3 1 0]
 [0 1 1 4 2 0]
 [0 2 3 3 2 0]
 [0 1 2 2 5 0]]


In [4]:
c0=np.mean(all_feature,0)
print(c0)

[0.  1.7 2.4 3.  2.4 0.1]


In [5]:
distance0=np.linalg.norm(all_feature-c0,axis=1)
print(distance0)

[1.79443584 3.00333148 0.78740079 1.8493242  3.03644529 2.76043475
 2.00499377 1.90262976 0.78740079 2.90172363]


In [6]:
c1=all_feature[np.argmax(distance0)]
print(c1)

[0 1 2 2 5 1]


In [7]:
distance0=np.linalg.norm(all_feature-c0,axis=1)
print(distance0)
distance1=np.linalg.norm(all_feature-c1,axis=1)
print(distance1)

[1.79443584 3.00333148 0.78740079 1.8493242  3.03644529 2.76043475
 2.00499377 1.90262976 0.78740079 2.90172363]
[3.         5.19615242 3.60555128 3.60555128 0.         5.29150262
 4.79583152 3.87298335 3.60555128 1.        ]


In [8]:
c2=all_feature[np.argmax(distance0+distance1)]
print(c2)

[0 0 2 5 1 0]


In [9]:
iters=2000
result=np.zeros(10)
for i in range(iters):
    distance= np.array([np.linalg.norm(all_feature-c0,axis=1),
                    np.linalg.norm(all_feature-c1,axis=1),
                    np.linalg.norm(all_feature-c2,axis=1)])
    cluster = np.argmin(distance,axis=0)
    if (cluster == result).all():
        print(cluster)
        print("result no change")
        break
    print(cluster)
    cluster0=[]
    cluster1=[]
    cluster2=[]
    index=np.argwhere(cluster==0)
    for i in index:
        cluster0.append(all_feature[i])
    index=np.argwhere(cluster==1)
    for i in index:
        cluster1.append(all_feature[i])
    index=np.argwhere(cluster==2)
    for i in index:
        cluster2.append(all_feature[i])
    c0_old=c0
    c1_old=c1
    c2_old=c2
    c0=np.mean(cluster0,axis=0)
    c1=np.mean(cluster1,axis=0)
    c2=np.mean(cluster2,axis=0)
    if (c0==c0_old).all() and (c1==c1_old).all() and (c2==c2_old).all():
        print("cluster no change")
        break
    result=cluster
    
    

[0 2 0 0 1 0 0 0 0 1]
[0 2 0 0 1 0 0 2 0 1]
[0 2 0 2 1 0 0 2 0 1]
[0 2 0 2 1 0 0 2 0 1]
result no change


In [10]:
print(result)

[0 2 0 2 1 0 0 2 0 1]
